[2020-03-24 19:26:56,933: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2020-03-24 19:26:56,937: DEBUG/MainProcess] | Worker: Building graph...
[2020-03-24 19:26:56,937: DEBUG/MainProcess] | Worker: New boot order: {Beat, Timer, Hub, Pool, Autoscaler, StateDB, Consumer}
[2020-03-24 19:26:56,959: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2020-03-24 19:26:56,959: DEBUG/MainProcess] | Consumer: Building graph...
[2020-03-24 19:26:57,047: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Events, Mingle, Gossip, Agent, Heart, Tasks, Control, event loop}
[2020-03-24 19:26:57,073: DEBUG/MainProcess] | Worker: Starting Pool
[2020-03-24 19:26:57,121: DEBUG/MainProcess] ^-- substep ok
[2020-03-24 19:26:57,122: DEBUG/MainProcess] | Worker: Starting Consumer
[2020-03-24 19:26:57,122: DEBUG/MainProcess] | Consumer: Starting Connection
[2020-03-24 19:27:27,405: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 2.00 seconds... (1/100)

[2020-03-24 19:27:59,678: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 4.00 seconds... (2/100)

[2020-03-24 19:28:33,986: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 6.00 seconds... (3/100)

[2020-03-24 19:29:10,298: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 8.00 seconds... (4/100)

[2020-03-24 19:29:48,601: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 10.00 seconds... (5/100)

[2020-03-24 19:30:28,895: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 12.00 seconds... (6/100)

[2020-03-24 19:31:11,183: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 14.00 seconds... (7/100)

[2020-03-24 19:31:55,514: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 16.00 seconds... (8/100)

[2020-03-24 19:32:41,840: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 18.00 seconds... (9/100)

[2020-03-24 19:33:30,158: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 20.00 seconds... (10/100)

[2020-03-24 19:34:20,471: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 22.00 seconds... (11/100)

[2020-03-24 19:34:42,040: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2020-03-24 19:34:42,042: DEBUG/MainProcess] | Worker: Building graph...
[2020-03-24 19:34:42,043: DEBUG/MainProcess] | Worker: New boot order: {Beat, StateDB, Timer, Hub, Pool, Autoscaler, Consumer}
[2020-03-24 19:34:42,057: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2020-03-24 19:34:42,058: DEBUG/MainProcess] | Consumer: Building graph...
[2020-03-24 19:34:42,092: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Events, Heart, Mingle, Gossip, Tasks, Control, Agent, event loop}
[2020-03-24 19:34:42,116: DEBUG/MainProcess] | Worker: Starting Pool
[2020-03-24 19:34:42,170: DEBUG/MainProcess] ^-- substep ok
[2020-03-24 19:34:42,173: DEBUG/MainProcess] | Worker: Starting Consumer
[2020-03-24 19:34:42,174: DEBUG/MainProcess] | Consumer: Starting Connection
[2020-03-24 19:35:12,459: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 2.00 seconds... (1/100)

[2020-03-24 19:35:44,738: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 4.00 seconds... (2/100)

[2020-03-24 19:36:18,992: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 6.00 seconds... (3/100)

[2020-03-24 19:36:55,270: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 8.00 seconds... (4/100)

[2020-03-24 19:37:33,564: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 10.00 seconds... (5/100)

[2020-03-24 19:38:13,855: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 12.00 seconds... (6/100)

[2020-03-24 19:38:56,128: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 14.00 seconds... (7/100)

[2020-03-24 19:39:40,439: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 16.00 seconds... (8/100)

[2020-03-24 19:40:26,739: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 18.00 seconds... (9/100)

[2020-03-24 19:41:15,082: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 20.00 seconds... (10/100)

[2020-03-24 19:42:05,347: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 22.00 seconds... (11/100)

[2020-03-24 19:42:57,652: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 24.00 seconds... (12/100)

[2020-03-24 19:43:51,973: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 26.00 seconds... (13/100)

[2020-03-24 19:44:48,268: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 28.00 seconds... (14/100)

[2020-03-24 19:45:46,607: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 30.00 seconds... (15/100)

[2020-03-24 19:46:46,963: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 19:47:49,358: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 19:48:51,695: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 19:49:54,086: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 19:50:56,442: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 19:51:58,812: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 19:53:01,187: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 19:54:03,559: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 19:55:05,917: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 19:56:08,415: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 19:57:10,774: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 19:58:13,139: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 19:59:15,498: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:00:17,842: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:01:20,221: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:02:22,602: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:03:24,936: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:04:27,307: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:05:29,685: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:06:32,030: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:07:34,408: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:08:36,777: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:09:39,121: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:10:41,469: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:11:43,825: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:12:46,181: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:13:48,582: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:14:50,973: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:15:53,346: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:16:55,704: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:17:58,056: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:19:00,392: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:20:02,790: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:21:05,197: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:22:07,579: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:23:09,970: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:24:12,341: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:25:14,682: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:26:17,039: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:27:19,381: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:28:21,733: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:29:24,078: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:30:26,442: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:31:28,826: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:32:31,145: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:33:33,485: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:34:35,832: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:35:38,210: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:36:40,589: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:37:42,962: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:38:45,301: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:39:47,642: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:40:50,019: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:41:52,342: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:42:54,687: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:43:57,029: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:44:59,342: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:46:01,701: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:47:04,049: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:48:06,419: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:49:08,779: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:50:11,146: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:51:13,532: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:52:15,896: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:53:18,276: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:54:20,614: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:55:22,908: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:56:25,189: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:57:27,525: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:58:29,829: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 20:59:32,164: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 21:00:34,557: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 21:01:36,889: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 21:02:39,235: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 21:03:41,699: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 21:04:44,045: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 21:05:46,502: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 21:06:48,852: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 21:07:51,183: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 21:08:53,508: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 21:09:55,850: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 21:10:58,179: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 21:12:00,500: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 21:13:02,802: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 21:14:05,107: ERROR/MainProcess] consumer: Cannot connect to mongodb://rss_backend_1:27017/jobs: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known.
Trying again in 32.00 seconds... (16/100)

[2020-03-24 21:15:07,467: CRITICAL/MainProcess] Unrecoverable error: OperationalError('rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known')
Traceback (most recent call last):
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/kombu/transport/virtual/base.py", line 921, in create_channel
    return self._avail_channels.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/kombu/connection.py", line 439, in _reraise_as_library_errors
    yield
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/kombu/connection.py", line 430, in ensure_connection
    callback, timeout=timeout)
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/kombu/utils/functional.py", line 344, in retry_over_time
    return fun(*args, **kwargs)
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/kombu/connection.py", line 283, in connect
    return self.connection
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/kombu/connection.py", line 839, in connection
    self._connection = self._establish_connection()
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/kombu/connection.py", line 794, in _establish_connection
    conn = self.transport.establish_connection()
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/kombu/transport/virtual/base.py", line 941, in establish_connection
    self._avail_channels.append(self.create_channel(self))
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/kombu/transport/virtual/base.py", line 923, in create_channel
    channel = self.Channel(connection)
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/kombu/transport/mongodb.py", line 120, in __init__
    self.client
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/kombu/transport/mongodb.py", line 359, in client
    return self._create_client()
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/kombu/transport/mongodb.py", line 351, in _create_client
    database = self._open()
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/kombu/transport/mongodb.py", line 310, in _open
    version_str = mongoconn.server_info()['version']
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1868, in server_info
    session=session)
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/pymongo/database.py", line 730, in command
    read_preference, session) as (sock_info, slave_ok):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1298, in _socket_for_reads
    server = self._select_server(read_preference, session)
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1253, in _select_server
    server = topology.select_server(server_selector)
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/pymongo/topology.py", line 235, in select_server
    address))
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/pymongo/topology.py", line 193, in select_servers
    selector, server_timeout, address)
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/pymongo/topology.py", line 209, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/celery/worker/consumer/connection.py", line 23, in start
    c.connection = c.connect()
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 405, in connect
    conn = self.connection_for_read(heartbeat=self.amqheartbeat)
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 412, in connection_for_read
    self.app.connection_for_read(heartbeat=heartbeat))
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 439, in ensure_connected
    callback=maybe_shutdown,
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/kombu/connection.py", line 430, in ensure_connection
    callback, timeout=timeout)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/kombu/connection.py", line 444, in _reraise_as_library_errors
    sys.exc_info()[2])
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/vine/five.py", line 194, in reraise
    raise value.with_traceback(tb)
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/kombu/connection.py", line 439, in _reraise_as_library_errors
    yield
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/kombu/connection.py", line 430, in ensure_connection
    callback, timeout=timeout)
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/kombu/utils/functional.py", line 344, in retry_over_time
    return fun(*args, **kwargs)
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/kombu/connection.py", line 283, in connect
    return self.connection
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/kombu/connection.py", line 839, in connection
    self._connection = self._establish_connection()
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/kombu/connection.py", line 794, in _establish_connection
    conn = self.transport.establish_connection()
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/kombu/transport/virtual/base.py", line 941, in establish_connection
    self._avail_channels.append(self.create_channel(self))
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/kombu/transport/virtual/base.py", line 923, in create_channel
    channel = self.Channel(connection)
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/kombu/transport/mongodb.py", line 120, in __init__
    self.client
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/kombu/transport/mongodb.py", line 359, in client
    return self._create_client()
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/kombu/transport/mongodb.py", line 351, in _create_client
    database = self._open()
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/kombu/transport/mongodb.py", line 310, in _open
    version_str = mongoconn.server_info()['version']
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1868, in server_info
    session=session)
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/pymongo/database.py", line 730, in command
    read_preference, session) as (sock_info, slave_ok):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1298, in _socket_for_reads
    server = self._select_server(read_preference, session)
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1253, in _select_server
    server = topology.select_server(server_selector)
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/pymongo/topology.py", line 235, in select_server
    address))
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/pymongo/topology.py", line 193, in select_servers
    selector, server_timeout, address)
  File "/Users/dustinwilson/Desktop/RSS/env/lib/python3.7/site-packages/pymongo/topology.py", line 209, in _select_servers_loop
    self._error_message(selector))
kombu.exceptions.OperationalError: rss_backend_1:27017: [Errno 8] nodename nor servname provided, or not known
[2020-03-24 21:15:07,562: DEBUG/MainProcess] | Worker: Closing Pool...
[2020-03-24 21:15:07,985: DEBUG/MainProcess] | Worker: Closing Consumer...
[2020-03-24 21:15:07,985: DEBUG/MainProcess] | Worker: Stopping Consumer...
[2020-03-24 21:15:07,988: DEBUG/MainProcess] | Worker: Stopping Pool...
[2020-03-24 21:15:08,650: DEBUG/MainProcess] | Consumer: Shutdown Control...
[2020-03-24 21:15:08,654: DEBUG/MainProcess] | Consumer: Shutdown Tasks...
[2020-03-24 21:15:08,655: DEBUG/MainProcess] | Consumer: Shutdown Heart...
[2020-03-24 21:15:08,657: DEBUG/MainProcess] | Consumer: Shutdown Events...
[2020-03-24 21:15:08,659: DEBUG/MainProcess] | Consumer: Shutdown Connection...
